apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld
      app.kubernetes.io/instance: helloworld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld
        app.kubernetes.io/instance: helloworld
    spec:
      containers:
        - name: helloworld
          image: asia.gcr.io/poc-innovation-iot/helloworld
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources: 
            limits: 
              cpu: 500m
              memory: 128Mi
            requests: 
              cpu: 250m
              memory: 6