apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
namespace: deep-training
images:
- name: asia.gcr.io/poc-innovation-iot/gitlab-runner-example-deep
  newTag: 1e65218b
