apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: helloworld
    app.kubernetes.io/instance: helloworld
